---
development:
  cloud_name: dnlrqhwxv
  api_key: '297178136454818'
  api_secret: Oy2xBDbu-RNU8apWg_O5g7IlxD8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dnlrqhwxv
  api_key: '297178136454818'
  api_secret: Oy2xBDbu-RNU8apWg_O5g7IlxD8
  enhance_image_tag: true
  static_file_support: true
  secure: true
test:
  cloud_name: dnlrqhwxv
  api_key: '297178136454818'
  api_secret: Oy2xBDbu-RNU8apWg_O5g7IlxD8
  enhance_image_tag: true
  static_file_support: false
